service:
  name: ${self:custom.name}

custom:
  ${file(./sls.config.js)}

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  deploymentBucket:
    name: ${self:custom.bucket}
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  hello:
    handler: src/functions/hello.handler
    environment:
      TEST_VAR: ${self:custom.param1}
    events:
      - http:
          method: get
          path: hello
